[package]
name = "themelio-stf"
version = "0.4.4-alpha.0"
authors = ["Themelio Labs"]
edition = "2018"

description = "Core state-transition function and data structures for Themelio"
license = "MPL-2.0"
repository = "https://github.com/themeliolabs/themelio-stf"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.arbitrary]
version = "1"
features = ["derive"]

#[dependencies.cached]
#version="0.23.0"
#default-features = false
#eatures=["proc_macro"]

[dependencies.genawaiter]
version = "0.99.1"
default-features = false
features=[]

[dependencies.im]
version = "15.0.0"
features = ["serde"]

[dependencies.serde]
version = "1.0.126"
features = ["derive"]


[dependencies]
defmac = "0.2.1"
hex = "0.4.3"
stdcode="0.1.2"
dashmap="4.0.2"
derive_more="0.99"
ethnum = "1.0.3"
log = "0.4.14"
novasmt = "0.1.6"
num = "0.3.1"
num_enum = "0.5.1"
once_cell = "1.7.2"
parking_lot= "0.11.1"
rayon = "1.5.1"
rustc-hash = "1.1.0"
scopeguard = "1"
serde_repr = "0.1.7"
smallvec = "1.6.1"
stacker ="0.1"
tap ="1"
thiserror = "1.0.26"
tmelcrypt="0.1"

[target.'cfg(fuzzing)'.dependencies] 
env_logger ="0.8"
honggfuzz ="0.5"

[dev-dependencies]
criterion = "0.3"
beaver = "1.0.0"
chrono = { version = "0.4.19", features = ["serde"] }
lazy_static = "1.4.0"
logos = "0.12.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
rand = "0.8.4"
rstest = "0.10.0"


[[bench]]
name = "bench"
harness = false
